### ISSUE TITLE
Le storelocator et le tunnel propose les magasins désactivés

### ISSUE THREAD

**Issue by garensmile** [Smile-SA/magento2-module-store-delivery#1]
![screenshot - 08092017 - 11 32 17](https://user-images.githubusercontent.com/29067543/30206336-1fb16a4c-948c-11e7-83fa-b160b168dabd.png)
![screenshot - 08092017 - 11 32 58](https://user-images.githubusercontent.com/29067543/30206352-282a2d94-948c-11e7-9bae-f595b5f2151c.png)
![screenshot - 08092017 - 11 32 05](https://user-images.githubusercontent.com/29067543/30206353-2854f826-948c-11e7-829f-2942468622af.png)

**Comment by romainruaud** [comment]
Fixé dans la dernière version
