### ISSUE TITLE
IE 11 : la carte ne s'affiche pas

### ISSUE THREAD

**Issue by nelero** [Smile-SA/magento2-module-store-delivery#12]
Sur internet explorer (11 dans le cas du test) la carte ne s'affiche pas et génère des erreurs javascript.
Sur Firefox ou Chrome, la carte OpenStreetMap s'affiche bien à contexte équivalent.

### Preconditions
Dernière version du module
Dernières version des modules Smile prérequis (Store Locator, Map, retailer, ...)

Magento Version : CE 2.2.3

Module Store Delivery Version : 1.2.0

Environment : Production

Third party modules :
Smile Store Locator 1.3.3 (il faudrait l'ajouter dans les dépendances composer, car sinon ça plante à la compilation)
dépendances de Smile Store Locator
    - Smile/module-map 1.1.3
    - Smile/module-retailer 1.2.3
     - Willdurand/geocoder : 
dépendances de Smile Module Retailer 
     - smile/module-seller : 1.2.3

others : 
blackbird/monetico                               100.1.8   Monetico (CMCIC payment method)
boldcommerce/magento2-ordercomments              1.1.4     Magento 2 Module to add  a comment field above the place order button in ...
google/recaptcha                                 1.2.1     Client library for reCAPTCHA, a free service that protects websites from ...
hellobrave/cookiecompliance                      1.0.4     Magento 2 extension to insert a EU compliant implied consent cookie notif...
hellobrave/core                                  1.0.1     Magento 2 extension to support and register all other HelloBrave Magento ...
mageplaza/magento-2-blog-extension               2.6.2     Magento 2 Blog extension
mageplaza/module-core                            1.3.13    Mageplaza Core for Magento 2
mageplaza/module-google-recaptcha                1.0.2     Magento 2 Google Recaptcha Extension
owebia/magento2-module-advanced-setting-core     2.1.0     N/A
owebia/magento2-module-advanced-shipping-setting 2.0.7     N/A
temando/module-shipping-m2                       1.0.4     Temando multi-carrier shipping extension for Magento 2
yireo/magento2-googletagmanager2                 0.3.7     Add Google Tag Manager to Magento

### Steps to reproduce
1. Créer un vendeur (magasin) dans le menu vendeurs et indiquer qu'on peut etre livré
2. Activer le mode de retrait magasin en Bo
3. se connecter à un compte client
4. Ajouter des produits dans son panier et accéder à la première étape de livraison. A cette étape il y a déjà une erreur javascript (sur IE)
5. Le choix livraison à domicile ou en magasin est disponible
6. En cliquant sur expédier ici sur le choix magasin, la modale s'affiche avec la liste des magasins et la carte (sur Firefox et Chrome). Sur IE la carte ne s'affiche pas et il y a des erreurs javascript.
7. lors du clic sur un magasin, puis clic sur le bouton choisir ce magasin, rien ne se passe.

### Expected results
1. Le magasin devrait etre enregistré et la modale se fermer (comme sur Chrome  et FF)

### Actual result
La modale ne se ferme pas et des erreurs javascripts apparaissent : 
Impossible d’obtenir la propriété  « name » d’une référence null ou non définie
']' attendu
Map container not found.
Impossible d’obtenir la propriété  « getBounds » d’une référence null ou non définie
L’objet ne gère pas la propriété ou la méthode « getRetailerId »

**Comment by Fdec** [comment]
Hi @nelero 

Duplicate with the issues #32, so I close this issue.

**Comment by nelero** [comment]
Hi @Fdec ,
But since there no answer for months on both, can we expect a fix in a short delay ?
Thanks
