### ISSUE TITLE
Store pickup button disables when you select no store

### ISSUE THREAD

**Issue by pkisdar** [Smile-SA/magento2-module-store-delivery#13]
If you choose store pickup from checkout, don't select a store but click TWICE on the Select Store Address button, the modal window closes and you can't get it back unless you reload the page.

"Uncaught TypeError: Cannot read property 'getRetailerId' of null"

### Preconditions

Magento Version : 2.2.6 CE

Module Store Delivery Version : 1.2.0

Environment : Developer mode

Third party modules :

### Steps to reproduce

1. Choose store delivery from checkout.
2. DO NOT click any of the radio buttons of the stores in the list.
3. Click the Select Store Address button.
4. Click the Select Store Address button AGAIN

### Expected result

No store is selected so you can start it over, choose a store and be happy.

### Actual result

You can't open the store select modal window again.
-------
```
Uncaught TypeError: Cannot read property 'getRetailerId' of null
    at UiClass.hasAddress (store-delivery.js:80)
    at UiClass.selectAddress (store-delivery.js:59)
    at HTMLButtonElement.<anonymous> (knockout.js:3863)
    at HTMLButtonElement.dispatch (jquery.js:5226)
    at HTMLButtonElement.elemData.handle (jquery.js:4878)
hasAddress @ store-delivery.js:80
selectAddress @ store-delivery.js:59
(anonymous) @ knockout.js:3863
dispatch @ jquery.js:5226
elemData.handle @ jquery.js:4878
```
-------

**Comment by Fdec** [comment]
Thanks for the PR
