### ISSUE TITLE
Console JS Error on Checkout: Uncaught TypeError: this.getCarrierTitle is not a function

### ISSUE THREAD

**Issue by alexgayshunewave** [Smile-SA/magento2-module-store-delivery#27]
During our Magento upgrade from 2.2.9 to 2.3.3, we are upgrading smile modules to the latest versions. After update smile/module-store-delivery to the latest version "1.1.6", we are facing a blocking JS error which prevents from choosing Store Delivery option. 

Interesting fact is that the only update made in 1.1.6 release was the exact peace of code which leads to this error: https://github.com/Smile-SA/magento2-module-store-delivery/compare/1.1.5...1.1.6

### Preconditions

Module | Current Version
-- | --
smile/elasticsuite-for-retailer | 1.6.0 
smile/module-map | 1.1.7 (with patch)
smile/module-offer | 1.3.4
smile/module-retailer | 1.2.9
smile/module-retailer-offer | 1.5.1
smile/module-retailer-offer-inventory | 1.0.1
smile/module-seller | 1.2.6
smile/module-store-delivery | 1.1.6
smile/module-store-locator | 1.3.9.5

Magento Version : 2.3.3 EE
Environment : both developer and production modes

### Steps to reproduce
1. Add product to cart
2. Go to checkout 
3. Choose Store Delivery method and pick any store

### Expected result
1. No JS errors in console
2. User able to select store address

### Actual result
1. Console error
<img width="1440" alt="Screen Shot 2020-01-09 at 6 19 13 pm" src="https://user-images.githubusercontent.com/48237040/72046489-9cb5b680-330c-11ea-9611-116181af25e6.png">

**Comment by Fdec** [comment]
Hi @alexgayshunewave 

Thanks for your issue, it's fixe on release 1.1.7
