### ISSUE TITLE
Checkout not possible because of fatal error: Call to a member function getCarrierCode() on boolean

### ISSUE THREAD

**Issue by NoorulBhoelai** [Smile-SA/magento2-module-store-delivery#9]
I am testing the checkout but we are getting a fatal error in Magento version 2.2.3.

Can you please take a look? Even when the shipping method is disabled, the checkout does not work. The shop keeps loading while doing a checkout. Not being able to checkout.

[16-Aug-2018 15:07:26 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getCarrierCode() on boolean in .../vendor/smile/module-store-delivery/Observer/QuoteSubmit.php:64
Stack trace:
#0 .../vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Smile\StoreDelivery\Observer\QuoteSubmit->execute(Object(Magento\Framework\Event\Observer))
#1 .../vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Smile\StoreDelivery\Observer\QuoteSubmit), Object(Magento\Framework\Event\Observer))
#2 .../vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#3 .../vendor/smile/module-store-delivery/Observer/QuoteSubmit.php on line 64

**Comment by delyriand** [comment]
Hi @NoorulBhoelai ,

Thank you for report this issue.
Do you have the same error when "store delivery" shipping method is enabled?

But, i confirm when this method is disabled, i have the error. We will seek to fix this problem.

Best regard

**Comment by NoorulBhoelai** [comment]
When the "Store Delivery" shipping method is enabled we don't have the error. 

Kind Regard

**Comment by romainruaud** [comment]
It's my mistake :)

line 64 is : 

```
$carrier    = $this->carrierFactory->getIfActive($methodCode);
```

And then we do things on `$carrier` directly while it could be equal to `false` if the carrier is not active.

Should be easy to fix.
